"""Fail when ``TEST_COVERAGE_GAPS.md`` no longer matches a real measurement.

The document quoted a single headline percentage that nobody re-measured, so it
was allowed to rot: the numbers in it were true when written and false within
a few commits, and no test noticed (issue #295). Nothing about a markdown file
enforces its own accuracy, so the numbers are generated and this gate is the
enforcement. ``--write`` regenerates the block between the
``<!-- coverage:begin -->`` / ``<!-- coverage:end -->`` markers; the default run
re-measures and fails when the document disagrees with what the suite actually
does today.

The block is built by ``build_block`` and nothing else -- the writer and the
checker read the same function, so they cannot drift apart. ``tests/
test_coverage_doc.py`` checks the document's own internal consistency
arithmetically, with no coverage run, so the common mistake (editing a number by
hand) is caught in about a second rather than at the end of a full suite.

Exit codes:
  0  the document matches the fresh measurement (or ``--write`` regenerated it)
  1  the document is stale; a unified diff and the module-level delta print
  2  the measurement itself failed, or the document has no usable block

One consequence of the gate measuring the same suite the document describes:
`tests/test_coverage_doc.py` is part of that suite and polices the very block
`--write` regenerates, so a stale block makes those tests fail. `--write`
tolerates exactly that -- every failure in that one module, and nothing else
(see `staleness_failures`) -- so a stale document can be repaired in one
command, with the whole suite still running and the `Suite:` line still read
from it. Any other red run is a real failure and leaves the document alone.

No ``app`` import, no network, no hardcoded percentage: everything in the
document comes from the run this script just performed.
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import platform
import re
import subprocess
import sys
import tempfile
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

# Resolved from __file__, never from the caller's cwd: the gate has to measure
# and compare the same tree no matter where it is invoked from (CI runs it with
# working-directory: backend, a developer runs it from the repo root).
BACKEND_DIR = Path(__file__).resolve().parents[1]
DOCUMENT = BACKEND_DIR / "TEST_COVERAGE_GAPS.md"

COVERAGE_BEGIN = "<!-- coverage:begin -->"
COVERAGE_END = "<!-- coverage:end -->"
GAPS_BEGIN = "<!-- gaps:begin -->"
GAPS_END = "<!-- gaps:end -->"

GENERATED_NOTICE = (
    "<!-- Generated by `python scripts/measure_coverage.py --write`. Do not hand-edit. -->"
)
# The human-readable twin of MEASUREMENT_ARGS below: both describe the same run,
# so neither is written down twice.
COMMAND_LINE = "Command: `python -m pytest --cov=app --cov-report=term-missing`"

# The interpreter that produced the block. Statement counts are a property of
# the source AND the parser: CPython 3.11 finds 5137 statements in app/ where
# 3.14 finds 5075, from byte-identical source, and the difference is identical
# under coverage 7.15.4 and 7.16.2. A block written on one and compared on the
# other is a 62-statement diff with no visible cause, which is how a green
# local run and a red CI run coexisted unnoticed. Recording it lets the gate
# name the mismatch instead of printing arithmetic.
MEASURED_WITH_PREFIX = "Measured with: "


def coverage_version() -> str:
    try:
        import coverage
    except ModuleNotFoundError:
        return "not installed"
    return getattr(coverage, "__version__", "unknown")


def measured_with_line() -> str:
    """The `Measured with:` line naming the interpreter and coverage.py."""
    return f"{MEASURED_WITH_PREFIX}Python {platform.python_version()}, coverage {coverage_version()}"


MEASURED_WITH_RE = re.compile(rf"^{re.escape(MEASURED_WITH_PREFIX)}(?P<detail>.+)$")

# The interpreter the committed block is expected to have been measured under.
# It is the one CI uses (actions/setup-python, python-version "3.11"), the one
# backend/ruff.toml targets (py311) and the one the README documents, so the
# block is written under it rather than under whatever the author's box has.
TARGET_PYTHON = "python3.11"

# Run by the gate itself (with the JSON report swapped in, so nothing has to be
# parsed out of a terminal report) and echoed in the document as `Command:`.
MEASUREMENT_ARGS = ("-m", "pytest", "--cov=app")

# The `Suite:` line is ordered and zero-filled so a dropped count is a diff, not
# a sentence.
SUITE_COUNTS = ("passed", "skipped", "failed", "errors", "xfailed", "xpassed")

# pytest prints "1 error", the document prints the plural.
_SUITE_LABELS = {
    "passed": "passed",
    "skipped": "skipped",
    "failed": "failed",
    "error": "errors",
    "errors": "errors",
    "xfailed": "xfailed",
    "xpassed": "xpassed",
}
_SUITE_COUNT_RE = re.compile(r"\b(\d+) (passed|failed|error|errors|skipped|xfailed|xpassed)\b")

ROW_RE = re.compile(
    r"^\| `(?P<module>app/[^`]+\.py)` \| (?P<percent>\d+\.\d)% \| "
    r"(?P<statements>\d+) \| (?P<missed>\d+) \| (?P<lines>[^|]*) \|$"
)
GAP_ENTRY_RE = re.compile(
    r"^- `(?P<module>app/[^`]+\.py)` — (?P<percent>\d+\.\d)% "
    r"\((?P<missed>\d+)/(?P<statements>\d+) statements uncovered\)\. ?(?P<prose>\S.*)$"
)
LINE_CITATION_RE = re.compile(r"\blines?\s+((?:\d+(?:-\d+)?)(?:,\s*\d+(?:-\d+)?)*)")

OUTPUT_TAIL_LINES = 40

# The one test module allowed to be red during a `--write` run: it polices the
# block that run is about to replace, so its failures are the staleness being
# repaired rather than a broken measurement. See `staleness_failures`.
DOC_POLICY = "tests/test_coverage_doc.py"

FAILED_NODE_RE = re.compile(r"^(?:FAILED|ERROR)\s+(?P<node>\S+)")


class GateError(RuntimeError):
    """The measurement or the document is unusable; the caller exits 2."""


@dataclass(frozen=True)
class ModuleRow:
    """One `app/**.py` module as the document's table has to print it."""

    module: str
    percent: float
    statements: int
    missed: int
    missing_lines: tuple[int, ...]


# --------------------------------------------------------------------------
# formatting primitives
# --------------------------------------------------------------------------


def format_percent(covered: int, statements: int) -> float:
    """Percentage to one decimal; a module with no statements is fully covered."""
    return 100.0 if statements == 0 else round(100 * covered / statements, 1)


def format_pct(percent: float) -> str:
    return f"{percent:.1f}%"


def compress_ranges(lines: Iterable[int]) -> str:
    """`[65, 66, 67, 96]` -> `"65-67, 96"`; empty -> the literal `none`."""
    ordered = sorted(set(lines))
    if not ordered:
        return "none"
    rendered: list[str] = []
    start = previous = ordered[0]
    for number in ordered[1:]:
        if number == previous + 1:
            previous = number
            continue
        rendered.append(str(start) if start == previous else f"{start}-{previous}")
        start = previous = number
    rendered.append(str(start) if start == previous else f"{start}-{previous}")
    return ", ".join(rendered)


def expand_ranges(text: str) -> set[int]:
    """Inverse of `compress_ranges`, for reading a table back out of the document."""
    stripped = text.strip()
    if stripped == "none":
        return set()
    covered: set[int] = set()
    for item in stripped.split(","):
        bounds = [int(part) for part in item.strip().split("-")]
        covered.update(range(bounds[0], bounds[-1] + 1))
    return covered


def format_suite(counts: dict[str, int]) -> str:
    return ", ".join(f"{counts[name]} {name}" for name in SUITE_COUNTS)


def error_handling_lines(source: Sequence[str], missing: Iterable[int]) -> list[int]:
    """The uncovered lines that are an `except` or a `raise`.

    A missing line number past the end of the file is a GateError, not a skip:
    that means the document (or the source it describes) is stale, and silently
    dropping the line would let the staleness survive another round.
    """
    hits: list[int] = []
    for number in missing:
        if number > len(source):
            raise GateError(
                f"uncovered line {number} is past the end of the source file "
                f"({len(source)} lines): the document is stale"
            )
        text = source[number - 1].strip()
        if text.startswith(("except", "raise")):
            hits.append(number)
    return hits


# --------------------------------------------------------------------------
# measurement
# --------------------------------------------------------------------------


def run_suite(tmp_dir: Path) -> tuple[subprocess.CompletedProcess[str], Path]:
    """Run the suite under pytest-cov, writing every artifact into `tmp_dir`."""
    report_path = tmp_dir / "coverage.json"
    command = [
        sys.executable,
        *MEASUREMENT_ARGS,
        f"--cov-report=json:{report_path}",
        "-p",
        "no:cacheprovider",
    ]
    # no:cacheprovider keeps .pytest_cache out of the repo, and COVERAGE_FILE
    # keeps .coverage out of it too -- the gate must not leave the tree dirty,
    # and a developer's existing .coverage must not be the one being read.
    env = {**os.environ, "COVERAGE_FILE": str(tmp_dir / ".coverage")}
    print("$ " + " ".join(command), file=sys.stderr)
    completed = subprocess.run(
        command, cwd=BACKEND_DIR, env=env, capture_output=True, text=True, check=False
    )
    return completed, report_path


def parse_suite_counts(output: str) -> dict[str, int]:
    """The six counts from pytest's final summary line."""
    for line in reversed(output.splitlines()):
        matches = _SUITE_COUNT_RE.findall(line)
        if not matches:
            continue
        counts = dict.fromkeys(SUITE_COUNTS, 0)
        for number, label in matches:
            counts[_SUITE_LABELS[label]] += int(number)
        return counts
    raise GateError("no pytest summary line in the run output")


def module_name(key: str, root: Path) -> str:
    """A coverage-JSON file key as the document names it: `app/foo.py`.

    The report keys files relative to the rootdir, but only when the measured
    file really lives under it; a tree where `app` is a symlink (or a run with a
    different rootdir) yields absolute keys, and those must not leak a
    developer's home directory into a committed document.
    """
    path = Path(key)
    if path.is_absolute():
        try:
            return path.relative_to(root).as_posix()
        except ValueError as error:
            raise GateError(f"measured file {key} is not inside {root}") from error
    return path.as_posix()


def build_rows(report: dict, root: Path = BACKEND_DIR) -> list[ModuleRow]:
    """Every measured `app/**.py` module, least covered first, ties broken by path."""
    rows: list[ModuleRow] = []
    for key, data in report["files"].items():
        module = module_name(key, root)
        if not module.startswith("app/"):
            continue
        summary = data["summary"]
        statements = summary["num_statements"]
        missed = summary["missing_lines"]
        missing_lines = tuple(sorted(data["missing_lines"]))
        if len(missing_lines) != missed:
            raise GateError(
                f"{module}: the coverage JSON disagrees with itself "
                f"({missed} missing statements, {len(missing_lines)} missing lines)"
            )
        rows.append(
            ModuleRow(
                module=module,
                percent=format_percent(summary["covered_lines"], statements),
                statements=statements,
                missed=missed,
                missing_lines=missing_lines,
            )
        )
    totals = report["totals"]
    row_statements = sum(row.statements for row in rows)
    row_missed = sum(row.missed for row in rows)
    if (row_statements, row_missed) != (totals["num_statements"], totals["missing_lines"]):
        raise GateError(
            "partial measurement: the per-module rows sum to "
            f"{row_statements} statements / {row_missed} missed, the report totals say "
            f"{totals['num_statements']} / {totals['missing_lines']}"
        )
    rows.sort(key=lambda row: (row.percent, row.module))
    return rows


def build_block(report: dict, counts: dict[str, int], root: Path = BACKEND_DIR) -> str:
    """The full body of the generated block, markers excluded.

    This is the only place the document's numbers are produced. It takes no
    clock and no git state. It does record the measuring interpreter, because
    statement counts are interpreter-dependent: the same source yields 5137
    statements under 3.11 and 5075 under 3.14. Omitting it did not make the
    block reproducible, it only made the disagreement invisible.
    """
    rows = build_rows(report, root)
    statements = sum(row.statements for row in rows)
    missed = sum(row.missed for row in rows)
    overall = format_percent(statements - missed, statements)

    lines = [
        GENERATED_NOTICE,
        COMMAND_LINE,
        measured_with_line(),
        f"Suite: {format_suite(counts)}",
        "",
        f"Overall: {format_pct(overall)} ({missed} of {statements} statements uncovered)",
        "",
        "### Per-module coverage (least covered first)",
        "",
        "| Module | Coverage | Statements | Missed | Uncovered lines |",
        "| --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| `{row.module}` | {format_pct(row.percent)} | {row.statements} | {row.missed} | "
        f"{compress_ranges(row.missing_lines)} |"
        for row in rows
    )

    errors: list[tuple[str, list[int]]] = []
    for row in rows:
        source = (root / row.module).read_text(encoding="utf-8").splitlines()
        hits = error_handling_lines(source, row.missing_lines)
        if hits:
            errors.append((row.module, hits))

    lines.extend(["", "### Uncovered error-handling statements", ""])
    if not errors:
        lines.append("No uncovered error-handling statements.")
    else:
        total = sum(len(hits) for _, hits in errors)
        lines.append(
            f"`except` and `raise` statements that no test executes — "
            f"{total} of the {missed} uncovered statements:"
        )
        lines.append("")
        lines.extend(
            f"- `{module}`: {', '.join(str(number) for number in hits)}"
            for module, hits in errors
        )
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# document
# --------------------------------------------------------------------------


def find_block(text: str, begin: str, end: str) -> tuple[int, int]:
    """Line indices of a marker pair, with the counts a document must satisfy."""
    lines = text.splitlines()
    for marker in (begin, end):
        if lines.count(marker) != 1:
            raise GateError(
                f"{DOCUMENT.name} must contain exactly one {marker} line "
                f"(found {lines.count(marker)})"
            )
    start, stop = lines.index(begin), lines.index(end)
    if start >= stop:
        raise GateError(f"{DOCUMENT.name} has {end} before {begin}")
    return start, stop


def extract_block(text: str, begin: str, end: str) -> str:
    """The body between a marker pair, in the same shape `build_block` returns."""
    start, stop = find_block(text, begin, end)
    return "\n".join(text.splitlines()[start + 1 : stop]) + "\n"


def replace_block(text: str, begin: str, end: str, body: str) -> str:
    """The document with `body` between the markers, markers untouched."""
    lines = text.splitlines()
    start, stop = find_block(text, begin, end)
    new_lines = lines[: start + 1] + body.splitlines() + lines[stop:]
    return "\n".join(new_lines) + "\n"


def parse_rows(block: str) -> list[ModuleRow]:
    """The table as the document currently prints it (rows that do not parse are skipped)."""
    rows: list[ModuleRow] = []
    for line in block.splitlines():
        match = ROW_RE.match(line)
        if not match:
            continue
        rows.append(
            ModuleRow(
                module=match["module"],
                percent=float(match["percent"]),
                statements=int(match["statements"]),
                missed=int(match["missed"]),
                missing_lines=tuple(sorted(expand_ranges(match["lines"]))),
            )
        )
    return rows


def module_delta(document_rows: Sequence[ModuleRow], measured: Sequence[str]) -> list[str]:
    """Human-readable module-level summary of what moved, in both directions."""
    documented = {row.module for row in document_rows}
    measured_set = set(measured)
    lines = [
        f"  missing from the table ({len(measured_set - documented)}): "
        + (", ".join(sorted(measured_set - documented)) or "none"),
        f"  in the table but not measured ({len(documented - measured_set)}): "
        + (", ".join(sorted(documented - measured_set)) or "none"),
    ]
    return lines


def failing_tests(output: str) -> list[str]:
    """Node ids from pytest's short test summary; `[]` when there is no summary."""
    failed: list[str] = []
    for line in output.splitlines():
        match = FAILED_NODE_RE.match(line)
        if match:
            failed.append(match.group("node"))
    return failed


def staleness_failures(output: str, counts: Mapping[str, int]) -> tuple[str, ...] | None:
    """The failures that are only the document's own consistency tests, else `None`.

    `tests/test_coverage_doc.py` polices the very block `--write` regenerates, so
    a stale block makes those tests fail -- the precise condition `--write`
    exists to repair. Treating that as a broken measurement deadlocks the gate:
    the document can never be regenerated, and the only way out is moving the
    test file aside by hand.

    The suite is still run whole. Nothing is deselected, because the `Suite:`
    line is parsed out of this very run's summary: dropping those tests would
    write a passed-count that no full run could ever reproduce, and check mode
    would then fail forever.

    Returns `None` -- fail closed, leave the document alone -- for any other
    reason a run can be red: a failing test elsewhere, a collection error, a
    short summary that does not account for every count pytest reported, or
    output with no summary at all.
    """
    failed = failing_tests(output)
    if not failed:
        return None
    if counts["errors"] or counts["failed"] != len(failed):
        return None
    if not all(node.startswith(DOC_POLICY) for node in failed):
        return None
    return tuple(failed)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite the generated block in place instead of failing on drift",
    )
    args = parser.parse_args(argv)

    try:
        document = DOCUMENT.read_text(encoding="utf-8")
        current = extract_block(document, COVERAGE_BEGIN, COVERAGE_END)
    except (OSError, GateError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    with tempfile.TemporaryDirectory(prefix="measure-coverage-") as raw_tmp:
        tmp_dir = Path(raw_tmp)
        try:
            completed, report_path = run_suite(tmp_dir)
            output = completed.stdout + completed.stderr
            counts = parse_suite_counts(output)
            tolerated = staleness_failures(output, counts) if args.write else None
            if completed.returncode != 0 and tolerated is None:
                print(
                    "error: the measurement run failed "
                    f"(pytest exit {completed.returncode}); the document was left untouched.",
                    file=sys.stderr,
                )
                print("\n".join(output.splitlines()[-OUTPUT_TAIL_LINES:]), file=sys.stderr)
                return 2
            if tolerated:
                # Those tests fail *because* of the block this run is about to
                # replace, and pass once it is replaced -- so counting them as
                # failed would write a `Suite:` line no clean run can ever
                # reproduce, leaving the gate permanently red. The rewrite does
                # not have to be right about that: the next check-mode run
                # re-measures for real and turns any mistake here into exit 1.
                counts = {**counts, "passed": counts["passed"] + len(tolerated), "failed": 0}
                print(
                    f"note: {len(tolerated)} failure(s) in {DOC_POLICY} are the document "
                    "being stale, which is what --write exists to repair. The block is "
                    f"written counting them as passed ({counts['passed']} projected); "
                    "the next check-mode run verifies that against a clean run.",
                    file=sys.stderr,
                )
            report = json.loads(report_path.read_text(encoding="utf-8"))
            block = build_block(report, counts)
        except (OSError, ValueError, GateError) as error:
            print(f"error: {error}", file=sys.stderr)
            return 2

    if args.write:
        updated = replace_block(document, COVERAGE_BEGIN, COVERAGE_END, block)
        if updated == document:
            print(f"{DOCUMENT.name} already matches the fresh measurement.")
            return 0
        DOCUMENT.write_text(updated, encoding="utf-8")
        print(f"Rewrote the generated block in {DOCUMENT}.")
        return 0

    if current == block:
        summary = next(line for line in block.splitlines() if line.startswith("Overall:"))
        print(f"{DOCUMENT.name} matches the fresh measurement. {summary}")
        return 0

    # Name the cause before the arithmetic. When the block was measured on a
    # different interpreter the diff is a wall of per-module statement counts
    # with nothing in common, and the only useful fact -- that no amount of
    # editing the document will fix it -- is not visible anywhere in it.
    committed = next(
        (m.group("detail") for line in current.splitlines() if (m := MEASURED_WITH_RE.match(line))),
        None,
    )
    running = measured_with_line()[len(MEASURED_WITH_PREFIX) :]
    if committed is not None and committed != running:
        print(
            f"error: the committed block was measured with {committed}, but this run is "
            f"measuring with {running}.",
            file=sys.stderr,
        )
        print(
            "Statement counts are interpreter-dependent (the same source yields 5137 "
            "statements under Python 3.11 and 5075 under 3.14), so this diff is not "
            "staleness, and re-running --write here would only trade one wrong "
            "interpreter for another.",
            file=sys.stderr,
        )
        print(
            f"Regenerate the block under the interpreter CI uses ({TARGET_PYTHON}): "
            f"{TARGET_PYTHON} -m pip install -r requirements.txt -r requirements-dev.txt",
            file=sys.stderr,
        )
        return 1

    print(f"{DOCUMENT.name} does not match the fresh measurement.")
    print("Re-run `python scripts/measure_coverage.py --write` to regenerate the block.")
    print("--- diff (document -> fresh measurement) ---")
    diff = difflib.unified_diff(
        current.splitlines(),
        block.splitlines(),
        fromfile=f"{DOCUMENT.name} (as committed)",
        tofile="freshly measured",
        lineterm="",
    )
    print("\n".join(diff))
    print("--- modules ---")
    print("\n".join(module_delta(parse_rows(current), [row.module for row in build_rows(report)])))
    return 1


if __name__ == "__main__":
    sys.exit(main())
