"""Fail when ``TEST_COVERAGE_GAPS.md`` no longer matches a real measurement.

The block between the coverage markers is generated; never hand-edit it.

Exit codes:
  0  the document matches the fresh measurement
  1  the document is stale
  2  the measurement failed, or the document has no usable block
  3  the interpreter is not the one the block must be measured under
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import platform
import re
import subprocess
import sys
import tempfile
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
DOCUMENT = BACKEND_DIR / "TEST_COVERAGE_GAPS.md"

COVERAGE_BEGIN = "<!-- coverage:begin -->"
COVERAGE_END = "<!-- coverage:end -->"
GAPS_BEGIN = "<!-- gaps:begin -->"
GAPS_END = "<!-- gaps:end -->"

GENERATED_NOTICE = (
    "<!-- Generated by `python scripts/measure_coverage.py --write`. Do not hand-edit. -->"
)
COMMAND_LINE = "Command: `python -m pytest --cov=app --cov-report=term-missing`"

# Statement counts are interpreter-dependent, so the block records its interpreter.
MEASURED_WITH_PREFIX = "Measured with: "


def coverage_version() -> str:
    try:
        import coverage
    except ModuleNotFoundError:
        return "not installed"
    return getattr(coverage, "__version__", "unknown")


def measured_with_line() -> str:
    return f"{MEASURED_WITH_PREFIX}Python {platform.python_version()}, coverage {coverage_version()}"


# Captures the interpreter alone so the coverage.py version beside it is ignored.
MEASURED_WITH_RE = re.compile(
    rf"^{re.escape(MEASURED_WITH_PREFIX)}(?P<interp>Python [\d.]+)(?:, .*)?$"
)

# The interpreter CI uses and ruff.toml targets; main() refuses any other.
TARGET_PYTHON = "python3.11"
TARGET_VERSION = (3, 11)

MEASUREMENT_ARGS = ("-m", "pytest", "--cov=app")

SUITE_COUNTS = ("passed", "skipped", "failed", "errors", "xfailed", "xpassed")

# pytest prints "1 error", the document prints the plural.
_SUITE_LABELS = {
    "passed": "passed",
    "skipped": "skipped",
    "failed": "failed",
    "error": "errors",
    "errors": "errors",
    "xfailed": "xfailed",
    "xpassed": "xpassed",
}
_SUITE_COUNT_RE = re.compile(r"\b(\d+) (passed|failed|error|errors|skipped|xfailed|xpassed)\b")

ROW_RE = re.compile(
    r"^\| `(?P<module>app/[^`]+\.py)` \| (?P<percent>\d+\.\d)% \| "
    r"(?P<statements>\d+) \| (?P<missed>\d+) \| (?P<lines>[^|]*) \|$"
)
GAP_ENTRY_RE = re.compile(
    r"^- `(?P<module>app/[^`]+\.py)` — (?P<percent>\d+\.\d)% "
    r"\((?P<missed>\d+)/(?P<statements>\d+) statements uncovered\)\. ?(?P<prose>\S.*)$"
)
LINE_CITATION_RE = re.compile(r"\blines?\s+((?:\d+(?:-\d+)?)(?:,\s*\d+(?:-\d+)?)*)")

OUTPUT_TAIL_LINES = 40

# The one module tolerated red during --write: it polices the block that run replaces.
DOC_POLICY = "tests/test_coverage_doc.py"

FAILED_NODE_RE = re.compile(r"^(?:FAILED|ERROR)\s+(?P<node>\S+)")


class GateError(RuntimeError):
    """The measurement or the document is unusable; the caller exits 2."""


@dataclass(frozen=True)
class ModuleRow:
    module: str
    percent: float
    statements: int
    missed: int
    missing_lines: tuple[int, ...]


def format_percent(covered: int, statements: int) -> float:
    return 100.0 if statements == 0 else round(100 * covered / statements, 1)


def format_pct(percent: float) -> str:
    return f"{percent:.1f}%"


def compress_ranges(lines: Iterable[int]) -> str:
    ordered = sorted(set(lines))
    if not ordered:
        return "none"
    rendered: list[str] = []
    start = previous = ordered[0]
    for number in ordered[1:]:
        if number == previous + 1:
            previous = number
            continue
        rendered.append(str(start) if start == previous else f"{start}-{previous}")
        start = previous = number
    rendered.append(str(start) if start == previous else f"{start}-{previous}")
    return ", ".join(rendered)


def expand_ranges(text: str) -> set[int]:
    stripped = text.strip()
    if stripped == "none":
        return set()
    covered: set[int] = set()
    for item in stripped.split(","):
        bounds = [int(part) for part in item.strip().split("-")]
        covered.update(range(bounds[0], bounds[-1] + 1))
    return covered


def format_suite(counts: dict[str, int]) -> str:
    return ", ".join(f"{counts[name]} {name}" for name in SUITE_COUNTS)


def error_handling_lines(source: Sequence[str], missing: Iterable[int]) -> list[int]:
    """The uncovered lines that are an `except` or a `raise`; a number past EOF raises."""
    hits: list[int] = []
    for number in missing:
        if number > len(source):
            raise GateError(
                f"uncovered line {number} is past the end of the source file "
                f"({len(source)} lines): the document is stale"
            )
        text = source[number - 1].strip()
        if text.startswith(("except", "raise")):
            hits.append(number)
    return hits


def run_suite(tmp_dir: Path) -> tuple[subprocess.CompletedProcess[str], Path]:
    report_path = tmp_dir / "coverage.json"
    command = [
        sys.executable,
        *MEASUREMENT_ARGS,
        f"--cov-report=json:{report_path}",
        "-p",
        "no:cacheprovider",
    ]
    # Keeps the repo clean and ignores a developer's existing .coverage.
    env = {**os.environ, "COVERAGE_FILE": str(tmp_dir / ".coverage")}
    print("$ " + " ".join(command), file=sys.stderr)
    completed = subprocess.run(
        command, cwd=BACKEND_DIR, env=env, capture_output=True, text=True, check=False
    )
    return completed, report_path


def parse_suite_counts(output: str) -> dict[str, int]:
    for line in reversed(output.splitlines()):
        matches = _SUITE_COUNT_RE.findall(line)
        if not matches:
            continue
        counts = dict.fromkeys(SUITE_COUNTS, 0)
        for number, label in matches:
            counts[_SUITE_LABELS[label]] += int(number)
        return counts
    raise GateError("no pytest summary line in the run output")


def module_name(key: str, root: Path) -> str:
    """A coverage-JSON key as the document names it; absolute keys are rebased onto `root`."""
    path = Path(key)
    if path.is_absolute():
        try:
            return path.relative_to(root).as_posix()
        except ValueError as error:
            raise GateError(f"measured file {key} is not inside {root}") from error
    return path.as_posix()


def build_rows(report: dict, root: Path = BACKEND_DIR) -> list[ModuleRow]:
    rows: list[ModuleRow] = []
    for key, data in report["files"].items():
        module = module_name(key, root)
        if not module.startswith("app/"):
            continue
        summary = data["summary"]
        statements = summary["num_statements"]
        missed = summary["missing_lines"]
        missing_lines = tuple(sorted(data["missing_lines"]))
        if len(missing_lines) != missed:
            raise GateError(
                f"{module}: the coverage JSON disagrees with itself "
                f"({missed} missing statements, {len(missing_lines)} missing lines)"
            )
        rows.append(
            ModuleRow(
                module=module,
                percent=format_percent(summary["covered_lines"], statements),
                statements=statements,
                missed=missed,
                missing_lines=missing_lines,
            )
        )
    totals = report["totals"]
    row_statements = sum(row.statements for row in rows)
    row_missed = sum(row.missed for row in rows)
    if (row_statements, row_missed) != (totals["num_statements"], totals["missing_lines"]):
        raise GateError(
            "partial measurement: the per-module rows sum to "
            f"{row_statements} statements / {row_missed} missed, the report totals say "
            f"{totals['num_statements']} / {totals['missing_lines']}"
        )
    rows.sort(key=lambda row: (row.percent, row.module))
    return rows


def build_block(report: dict, counts: dict[str, int], root: Path = BACKEND_DIR) -> str:
    """The only place the document's numbers are produced; reader and writer both use it."""
    rows = build_rows(report, root)
    statements = sum(row.statements for row in rows)
    missed = sum(row.missed for row in rows)
    overall = format_percent(statements - missed, statements)

    lines = [
        GENERATED_NOTICE,
        COMMAND_LINE,
        measured_with_line(),
        f"Suite: {format_suite(counts)}",
        "",
        f"Overall: {format_pct(overall)} ({missed} of {statements} statements uncovered)",
        "",
        "### Per-module coverage (least covered first)",
        "",
        "| Module | Coverage | Statements | Missed | Uncovered lines |",
        "| --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| `{row.module}` | {format_pct(row.percent)} | {row.statements} | {row.missed} | "
        f"{compress_ranges(row.missing_lines)} |"
        for row in rows
    )

    errors: list[tuple[str, list[int]]] = []
    for row in rows:
        source = (root / row.module).read_text(encoding="utf-8").splitlines()
        hits = error_handling_lines(source, row.missing_lines)
        if hits:
            errors.append((row.module, hits))

    lines.extend(["", "### Uncovered error-handling statements", ""])
    if not errors:
        lines.append("No uncovered error-handling statements.")
    else:
        total = sum(len(hits) for _, hits in errors)
        lines.append(
            f"`except` and `raise` statements that no test executes — "
            f"{total} of the {missed} uncovered statements:"
        )
        lines.append("")
        lines.extend(
            f"- `{module}`: {', '.join(str(number) for number in hits)}"
            for module, hits in errors
        )
    return "\n".join(lines) + "\n"


def find_block(text: str, begin: str, end: str) -> tuple[int, int]:
    lines = text.splitlines()
    for marker in (begin, end):
        if lines.count(marker) != 1:
            raise GateError(
                f"{DOCUMENT.name} must contain exactly one {marker} line "
                f"(found {lines.count(marker)})"
            )
    start, stop = lines.index(begin), lines.index(end)
    if start >= stop:
        raise GateError(f"{DOCUMENT.name} has {end} before {begin}")
    return start, stop


def extract_block(text: str, begin: str, end: str) -> str:
    start, stop = find_block(text, begin, end)
    return "\n".join(text.splitlines()[start + 1 : stop]) + "\n"


def replace_block(text: str, begin: str, end: str, body: str) -> str:
    lines = text.splitlines()
    start, stop = find_block(text, begin, end)
    new_lines = lines[: start + 1] + body.splitlines() + lines[stop:]
    return "\n".join(new_lines) + "\n"


def parse_rows(block: str) -> list[ModuleRow]:
    rows: list[ModuleRow] = []
    for line in block.splitlines():
        match = ROW_RE.match(line)
        if not match:
            continue
        rows.append(
            ModuleRow(
                module=match["module"],
                percent=float(match["percent"]),
                statements=int(match["statements"]),
                missed=int(match["missed"]),
                missing_lines=tuple(sorted(expand_ranges(match["lines"]))),
            )
        )
    return rows


def module_delta(document_rows: Sequence[ModuleRow], measured: Sequence[str]) -> list[str]:
    documented = {row.module for row in document_rows}
    measured_set = set(measured)
    lines = [
        f"  missing from the table ({len(measured_set - documented)}): "
        + (", ".join(sorted(measured_set - documented)) or "none"),
        f"  in the table but not measured ({len(documented - measured_set)}): "
        + (", ".join(sorted(documented - measured_set)) or "none"),
    ]
    return lines


def failing_tests(output: str) -> list[str]:
    failed: list[str] = []
    for line in output.splitlines():
        match = FAILED_NODE_RE.match(line)
        if match:
            failed.append(match.group("node"))
    return failed


def staleness_failures(output: str, counts: Mapping[str, int]) -> tuple[str, ...] | None:
    """The failures that are only DOC_POLICY's own, else `None`."""
    failed = failing_tests(output)
    if not failed:
        return None
    if counts["errors"] or counts["failed"] != len(failed):
        return None
    if not all(node.startswith(DOC_POLICY) for node in failed):
        return None
    return tuple(failed)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite the generated block in place instead of failing on drift",
    )
    args = parser.parse_args(argv)

    # Both modes, before measuring: a block written elsewhere still passes locally.
    if sys.version_info[:2] != TARGET_VERSION:
        # The version actually tested: the two accessors can disagree.
        running = ".".join(str(part) for part in sys.version_info[:3])
        print(
            f"error: this gate must be measured under {TARGET_PYTHON} "
            f"({TARGET_VERSION[0]}.{TARGET_VERSION[1]}), and this is {running}.",
            file=sys.stderr,
        )
        print(
            "Statement counts are interpreter-dependent, so a block measured "
            "elsewhere does not describe the same source. Install the pinned "
            "dependencies under the target interpreter and re-run: "
            f"{TARGET_PYTHON} -m pip install -r requirements.txt -r requirements-dev.txt",
            file=sys.stderr,
        )
        return 3

    try:
        document = DOCUMENT.read_text(encoding="utf-8")
        current = extract_block(document, COVERAGE_BEGIN, COVERAGE_END)
    except (OSError, GateError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    with tempfile.TemporaryDirectory(prefix="measure-coverage-") as raw_tmp:
        tmp_dir = Path(raw_tmp)
        try:
            completed, report_path = run_suite(tmp_dir)
            output = completed.stdout + completed.stderr
            counts = parse_suite_counts(output)
            tolerated = staleness_failures(output, counts) if args.write else None
            if completed.returncode != 0 and tolerated is None:
                print(
                    "error: the measurement run failed "
                    f"(pytest exit {completed.returncode}); the document was left untouched.",
                    file=sys.stderr,
                )
                print("\n".join(output.splitlines()[-OUTPUT_TAIL_LINES:]), file=sys.stderr)
                return 2
            if tolerated:
                # Counted as passed: no clean run could reproduce that Suite: line.
                counts = {**counts, "passed": counts["passed"] + len(tolerated), "failed": 0}
                print(
                    f"note: {len(tolerated)} failure(s) in {DOC_POLICY} are the document "
                    "being stale, which is what --write exists to repair. The block is "
                    f"written counting them as passed ({counts['passed']} projected); "
                    "the next check-mode run verifies that against a clean run.",
                    file=sys.stderr,
                )
            report = json.loads(report_path.read_text(encoding="utf-8"))
            block = build_block(report, counts)
        except (OSError, ValueError, GateError) as error:
            print(f"error: {error}", file=sys.stderr)
            return 2

    if args.write:
        updated = replace_block(document, COVERAGE_BEGIN, COVERAGE_END, block)
        if updated == document:
            print(f"{DOCUMENT.name} already matches the fresh measurement.")
            return 0
        DOCUMENT.write_text(updated, encoding="utf-8")
        print(f"Rewrote the generated block in {DOCUMENT}.")
        return 0

    if current == block:
        summary = next(line for line in block.splitlines() if line.startswith("Overall:"))
        print(f"{DOCUMENT.name} matches the fresh measurement. {summary}")
        return 0

    # Name the cause first: an interpreter mismatch diffs as a wall of counts.
    committed_interp = next(
        (m.group("interp") for line in current.splitlines() if (m := MEASURED_WITH_RE.match(line))),
        None,
    )
    running_interp = f"Python {platform.python_version()}"
    if committed_interp is not None and committed_interp != running_interp:
        print(
            f"error: the committed block was measured with {committed_interp}, but this "
            f"run is measuring with {running_interp}.",
            file=sys.stderr,
        )
        print(
            "Statement counts are interpreter-dependent (the same source yields 5135 "
            "statements under Python 3.11 and 5073 under 3.14), so this diff is not "
            "staleness, and re-running --write here would only trade one wrong "
            "interpreter for another.",
            file=sys.stderr,
        )
        print(
            f"Regenerate the block under the interpreter CI uses ({TARGET_PYTHON}): "
            f"{TARGET_PYTHON} -m pip install -r requirements.txt -r requirements-dev.txt",
            file=sys.stderr,
        )
        return 1

    print(f"{DOCUMENT.name} does not match the fresh measurement.")
    print("Re-run `python scripts/measure_coverage.py --write` to regenerate the block.")
    print("--- diff (document -> fresh measurement) ---")
    diff = difflib.unified_diff(
        current.splitlines(),
        block.splitlines(),
        fromfile=f"{DOCUMENT.name} (as committed)",
        tofile="freshly measured",
        lineterm="",
    )
    print("\n".join(diff))
    print("--- modules ---")
    print("\n".join(module_delta(parse_rows(current), [row.module for row in build_rows(report)])))
    return 1


if __name__ == "__main__":
    sys.exit(main())
