"""Fast query-string typo correction before embedding.

SymSpell dictionary-based correction over a corpus-derived token vocabulary
plus a curated entity list. The corrected string is used for embedding, query
expansion, cache keys and entity boost; tokens left uncorrected fall through
to the hybrid (dense + BM25) search layer, which absorbs mild typos naturally.

The vocabulary is generated by scripts/build_query_vocab.py (gzip JSON list of
[token, doc_count]) and loaded once per process. When the vocab file is absent
fix_query() is a silent no-op, so startup never depends on a one-time artifact.
"""
import gzip
import json
import logging
import os
import re

from app.rerank_boost import _BRAND_ENTITIES

logger = logging.getLogger("query_fix")

# Curated entities (companies, VCs, people) get a huge base count so they win
# SymSpell suggestions over equally-close corpus words.
EXTRA_ENTITIES = [
    "Flipkart", "Myntra", "Oyo", "Ola", "Uber", "Swiggy", "Zomato",
    "Paytm", "PhonePe", "Razorpay", "Cred", "Unacademy", "Vedantu",
    "Upgrad", "upGrad", "Curefit", "Cure.fit", "Practo", "PharmEasy",
    "Meesho", "ShareChat", "Moj", "Dailyhunt", "BharatPe", "Groww",
    "Zerodha", "PolicyBazaar", "Mamaearth", "Dunzo", "Rapido",
    "Ather", "Chargebee", "Freshworks", "Zoho", "Infosys", "TCS",
    "Wipro", "Reliance", "Tata", "Adani", "Lightspeed", "Peak XV",
    "Elevation", "Blume", "Chiratae", "Kalaari", "Nexus", "Matrix",
    "Khosla", "Prosus", "Temasek", "GIC", "KKR", "Blackstone",
    "Warburg", "TPG", "General Atlantic", "Coatue", "Dharwad",
    "Shriram", "Manipal", "Kinder", "ASK", "Edelweiss",
    "Venture Catalysts", "9Unicorns", "WaterBridge", "Alteria", "Stride",
    "Lendingkart", "BizGain", "Webmobi", "MakeMyTrip", "Goibibo",
    "Hacksaw", "Booongo", "Microgaming",
]

_ENTITIES = [*_BRAND_ENTITIES, *EXTRA_ENTITIES]
_NORMALIZED_ENTITIES = sorted(
    {
        re.sub(r"\s+", " ", e.strip().lower()).replace("'", "").replace("\u2019", "")
        for e in _ENTITIES
        if e.strip()
    },
    key=len,
    reverse=True,
)

# Word tokenizer mirroring the BM25 tokenizer (lowercased [a-z0-9] runs). The
# correction is spliced back into the original string, preserving punctuation.
_WORD_RE = re.compile(r"[a-z0-9]+", re.IGNORECASE)

# Curated entities always win over corpus words of equal edit distance.
_CURATED_COUNT = 10_000_000


def _normalize_entity(name: str) -> str:
    return re.sub(r"\s+", " ", name.strip().lower()).replace("'", "").replace("\u2019", "")


class QueryFixer:
    def __init__(
        self,
        vocab_path: str | None,
        max_edit: int = 2,
        min_count: int = 5,
        min_token_len: int = 3,
        entities: list[str] | None = None,
    ):
        self.max_edit = max_edit
        self.min_count = min_count
        self.min_token_len = min_token_len
        self._sym = None
        self._known: set[str] = set()
        self._build(vocab_path, entities or _NORMALIZED_ENTITIES)

    @staticmethod
    def _load_vocab(path: str | None) -> dict[str, int]:
        if not path or not os.path.isfile(path):
            return {}
        try:
            with gzip.open(path, "rt", encoding="utf-8") as f:
                rows = json.load(f)
            return {str(t): int(c) for t, c in rows if isinstance(t, str) and t and isinstance(c, (int, float))}
        except Exception as exc:  # noqa: BLE001 - degraded mode, never crash startup
            logger.warning("query_fix: vocab load failed (%s); continuing without it", exc)
            return {}

    def _build(self, vocab_path: str | None, entities: list[str]) -> None:
        from symspellpy import SymSpell

        vocab = self._load_vocab(vocab_path)
        entries = {_normalize_entity(t): int(c) for t, c in vocab.items()}
        for e in entities:
            norm = _normalize_entity(e)
            entries[norm] = max(entries.get(norm, 0), _CURATED_COUNT)
        if not entries:
            logger.info("query_fix: no vocabulary; disabled")
            return
        sym = SymSpell(max_dictionary_edit_distance=self.max_edit, prefix_length=7)
        sym.create_dictionary(entries)
        self._sym = sym
        self._known = set(entries)
        logger.info("query_fix: ready (%d terms, max_edit=%d)", len(entries), self.max_edit)

    def _allowed_distance(self, token: str) -> int:
        # Short tokens are risky to correct beyond one edit.
        return 1 if len(token) <= 4 else self.max_edit

    def fix(self, text: str) -> tuple[str, list[dict]]:
        """Return (corrected_text, [{"token","correction","distance","count"}])."""
        if self._sym is None or not text:
            return text, []
        fixes: list[dict] = []

        def repl(m: re.Match) -> str:
            word = m.group(0)
            low = word.lower()
            if len(low) < self.min_token_len or low.isdigit() or low in self._known:
                return word
            res = self._sym.lookup(low, verbosity=1, max_edit_distance=self._allowed_distance(low))
            if not res:
                return word
            sug = res[0]
            if sug.term == low or sug.distance == 0:
                return word
            if sug.distance > 0 and sug.count < self.min_count:
                return word
            corr = sug.term
            if word[:1].isupper():
                corr = corr[:1].upper() + corr[1:]
            fixes.append({
                "token": word,
                "correction": corr,
                "distance": sug.distance,
                "count": sug.count,
            })
            return corr

        return _WORD_RE.sub(repl, text), fixes


fixer: QueryFixer | None = None


def init_fixer(
    enabled: bool,
    vocab_path: str | None,
    max_edit: int = 2,
    min_count: int = 5,
    min_token_len: int = 3,
) -> None:
    """Construct the process-wide fixer (call once at startup)."""
    global fixer
    if not enabled:
        fixer = None
        return
    fixer = QueryFixer(vocab_path, max_edit=max_edit, min_count=min_count, min_token_len=min_token_len)


def fix_query(q: str) -> tuple[str, list[dict]]:
    """Correct/query strings in place. Returns (fixed_text, fixes); no-op when
    the fixer is disabled or the vocab artifact is missing."""
    if fixer is None:
        return q, []
    return fixer.fix(q)
